Refactored test from PhpBroweser to WebBrowser
hiqsol-attic/hiam pull request #4
Opened 2018-07-25 16:35 UTC by tafid

2018-07-30 16:18 UTC, SilverFire requested changes

2018-07-30 16:18 UTC, SilverFire commented on tests/acceptance/HiamBasicFunctionsCest.php
> +        $this->mailsDir = getcwd() . '/runtime/mail';
Yii::getAlias('@runtime/mail')

2018-07-30 16:18 UTC, SilverFire commented on tests/acceptance/HiamBasicFunctionsCest.php
> +            FileHelper::removeDirectory(Yii::getAlias('@runtime/mail'));
`$this->mailsDir`

2018-07-30 16:18 UTC, SilverFire commented on tests/acceptance/HiamBasicFunctionsCest.php
> +     * @before cleanUp
emailConfirm слился в login. Почему бы не оставить зависимость на логин? Этот тест не будет без логина ведь работать

2018-07-30 17:07 UTC, tafid commented on tests/acceptance/HiamBasicFunctionsCest.php
> +     * @before cleanUp
Уже поговорили

2018-07-31 07:27 UTC, tafid commented on tests/acceptance/HiamBasicFunctionsCest.php
> +     * @before cleanUp
уже обсудили в офлайне

2018-07-31 07:54 UTC, SilverFire approved these changes

2018-07-31 07:55 UTC, merged